var quizQuestion = [
  {
    question: 'What are variables used for in JavaScript Programs ?',
    option1: 'Storing numbers, dates, or other values',
    option2: 'Varying randomly',
    option3: 'Causing high-school algebra flashbacks',
    option4: 'None of the above',
    answer: '1',
  },
  {
    question: 'What should appear at the very end of your JavaScript ?',
    option1: 'The </script>',
    option2: 'The <script>',
    option3: 'The END statement',
    option4: 'None of the above',
    answer: '1',
  },
  {
    question:
      "Which of the following can't be done with client-side JavaScript ?",
    option1: 'Validating a form',
    option2: 'Sending a forms contents by email',
    option3: 'Storing the forms contents to a database file on the server',
    option4: 'None of the above',
    answer: '3',
  },
  {
    question:
      'Which of the following is not a valid JavaScript variable name ?',
    option1: '2names',
    option2: '_first_and_last_names',
    option3: 'FirstAndLast',
    option4: 'None of the above',
    answer: '1',
  },
  {
    question: 'What is the correct JavaScript syntax to write "Hello World" ?',
    option1: 'System.out.println("Hello World")',
    option2: 'println ("Hello World")',
    option3: 'document.write("Hello World")',
    option4: 'response.write("Hello World")',
    answer: '3',
  },
  {
    question: 'Which of the following best describes JavaScript ?',
    option1: 'a low-level programming language.',
    option2: 'a scripting language precompiled in the browser.',
    option3: 'a compiled scripting language',
    option4: 'an object-oriented scripting language.',
    answer: '4',
  },
  {
    question: 'Choose the client-side JavaScript object ?',
    option1: 'Database',
    option2: 'Cursor',
    option3: 'Client',
    option4: 'FileUpLoad',
    answer: '4',
  },
  {
    question: 'How to create a Date object in JavaScript ?',
    option1: 'dateObjectName = new Date([parameters])',
    option2: 'dateObjectName.new Date([parameters])',
    option3: 'dateObjectName := new Date([parameters])',
    option4: 'dateObjectName Date([parameters])',
    answer: '1',
  },
  {
    question: 'Which tag(s) can handle mouse events in Netscape ?',
    option1: '<IMG>',
    option2: '<A>',
    option3: '<BR>',
    option4: 'None of the above',
    answer: '2',
  },
  {
    question:
      'The JavaScript exception is available to the Java code as an instance of ?',
    option1: 'netscape.javascript.JSObject',
    option2: 'netscape.javascript.JSException',
    option3: 'netscape.plugin.JSException',
    option4: 'None of the above',
    answer: '2',
  },
];
